### ISSUE TITLE
opaque error

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/datavyu_scripts#2]
![screen shot 2015-07-07 at 11 42 02 am](https://cloud.githubusercontent.com/assets/11085620/8550227/59917344-249d-11e5-8d1b-956615fb2d7b.png)

**Comment by andreiamatuni** [comment]
Can I get a copy of the .opf file you're using? I'm unable to reproduce the error with the files I have.

**Comment by ebergelson** [comment]
opus/WorkingFiles/17_09/17_09_coderEB.opf

**Comment by andreiamatuni** [comment]
I just got home from lab, shift ended at 12, and opus only works on UR_Connected

**Comment by ebergelson** [comment]
then you can work on it tomorrow, no worries:)

**Comment by andreiamatuni** [comment]
So the problem here is that the "object" code is called "word" rather than "object". This can be changed in the code editor in Datavyu. The script depends on the codes having some standardized names since the values can only be accessed by the name of the code. I made the change to the .opf file locally and the script runs the way it's supposed to. I didn't change it on opus though.

**Comment by ebergelson** [comment]
got it. the next time you go into fixing anything in those scripts it'd be nice to get a clearer error message like "codes in column do not match expected codes: object, utterance_type, object_present, speaker"

**Comment by andreiamatuni** [comment]
I'll add a check to print this kind of message, but the old ugly errors will unfortunately still be there since they're basically built into Datavyu.
